FROM mysql:8.0.33

ENV MYSQL_USER=josueTeo
ENV MYSQL_PASSWORD=jts220220
ENV MYSQL_ROOT_PASSWORD=admin
ENV MYSQL_ROOT_HOST=%

COPY docker/script.sql /docker-entrypoint-initdb.d/

RUN echo "[mysqld]" >> /etc/mysql/my.cnf
RUN echo "log_error_verbosity = 3" >> /etc/mysql/my.cnf
RUN echo "character-set-server=utf8mb4" >> /etc/mysql/my.cnf
RUN echo "collation-server=utf8mb4_unicode_ci" >> /etc/mysql/my.cnf

EXPOSE 3306
